### PR TITLE
TT-7026 Add secret hashes

### PR DESCRIPTION
**Pull request by zalbiraw**
## Description

Currently, if you update secrets in from the values.yaml that does not trigger deployment updates. Adding the secrets hashes to the deployment annotation seems to be the recommended approach to solving this issue per helm chart docs

https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by buraksekili — APPROVED** [review]
lgtm! thanks @zalbiraw.

**Comment by buraksekili** [comment]
since #222 is already merged, i will change this PR's base branch to `master` again. FYI @zalbiraw 
This PR still requires testing from @singhpr.

**Comment by zalbiraw** [comment]
Thank you @buraksekili. I rebased the branch to master!

**Comment by buraksekili** [comment]
@zalbiraw sorry for you informing you late but can you please add a one-liner that explains your change on [CHANGELOG](https://github.com/TykTechnologies/tyk-helm-chart/blob/master/CHANGELOG.md)? sorry, it totally slipped my mind.

**Comment by zalbiraw** [comment]
@buraksekili done!

**Pull request merged**
