### PR TITLE
[TT-5702] Make security context fields configurable

### LINKED ISSUE #178: Add runAsUser e fsGroup securityContext configuration
Fixed value in template for 'runAsUser' and 'fsGroup' cannot be validated against security context constraint on some environment.

Example:
```
securityContext:
        runAsUser: 1000
        fsGroup: 2000
```

To be:
```
securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
```

### PR DESCRIPTION
**Pull request by komalsukhani**
## Description

Added `securityContext` field for every component(Gateway, Dashboard, Pump, MDCB, TIB) in values.yaml file.
It is used to set PodSecurityContext field of corresponding deployments.

## Related Issue

[TT-5702](https://tyktech.atlassian.net/browse/TT-5702)
Resolves #178 

## Motivation and Context

helm charts failed to installed in OpenShift environment because securityContext values were hard-coded and OpenShift has securityContext constraints which requires UserID/fsGroup to be within specific range. 

Since securityContext is configurable user can easily install helm charts using those values.

## Test Coverage For This Change

Tested following on both OpenShift and non-OpenShift environment
1. Tyk-Pro successfully installed with and without custom securityContext values.
2. Tyk-Headless successfully installed with and without custom securityContext values.
3. Tyk-Hyrid successfully installed with and without custom securityContext values.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [x] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by zalbiraw — APPROVED** [review]
LGTM

**Review by buraksekili — APPROVED** [review]

**Comment by komalsukhani** [comment]
Don't merge it. Since we are planning to release it next helm release.

**Comment by zalbiraw** [comment]
@komalsukhani @buraksekili can we get this merged?

**Comment by komalsukhani** [comment]
@zalbiraw We are testing new flow in which tickets gets merged after QA tests it. So that our master branch is always in ready to release state(without any untested code).

**Comment by zalbiraw** [comment]
Amazing! I thought that was done tbh.

**Comment by zalbiraw** [comment]
Can we merge this now? 🙃

**Comment by buraksekili** [comment]
merged @zalbiraw 👍

**Pull request merged**
