### PR TITLE
allow more flexible expression of extraEnv

### PR DESCRIPTION
**Pull request by drpebcak**
This allows things like setting vars from configmaps/secrets/downward api/etc.

### CODE REVIEW

**Review by abhishiekgowtham — CHANGES_REQUESTED** [review]
Thanks for improving the helm charts @drpebcak! Can you fix the failing tests please? Other than it lgtm.

**Comment by drpebcak** [comment]
@abhishiekgowtham I don't think these test failures have anything to do with my changes. The `extraEnvs` change I am making has no default values in the chart.. so the rendered manifests are the same now as they were before. The output from the github jobs is not really super helpful either, but it seems like something unrelated is going wrong in the post-install script.

**Comment by abhishiekgowtham** [comment]
@drpebcak The CI tests runs on every PR by explicitly checking out the branch (on the left side) so all the checks run against the changes made on that particular branch. If the output/logs on the tests isn't super helpful, I'd suggest adding some debug statements to the actions file to get some useful information.

I'm sorry, I can't accept this PR without all checks passing.

**Comment by asoorm** [comment]
> @drpebcak The CI tests runs on every PR by explicitly checking out the branch (on the left side) so all the checks run against the changes made on that particular branch. If the output/logs on the tests isn't super helpful, I'd suggest adding some debug statements to the actions file to get some useful information.
> 
> I'm sorry, I can't accept this PR without all checks passing.

Screenshot 2021-06-09 at 07 39 37

@abhishiekgowtham this is our bad. If we look at the test that fails, it is caused by a license expiry check. This pulls a GH secret, and because @drpebcak is not in the Tyk GitHub organization, the GH action does not have enough permissions to pull the Tyk License to validate it's expiry. As such, the test fails.

IMO, this is a big problem, because it means that nobody in the OS community can collaborate with this project.

**Comment by excieve** [comment]
@asoorm Thanks for bringing it up! We agreed to stop requiring the smoke tests for `tyk-pro` and `tyk-headless` for now, while keeping them on the `master` pushes. In the future we'll need to find a way to test these without having to require secrets. I don't think we can currently successfully test the Tyk Dashboard bootstrap without a valid license or Hybrid without a valid set of RPC creds.

**Comment by asoorm** [comment]
@excieve we have similar issue with Tyk Operator. The way we "worked around" the problem was for 2 actions to fire on every PR. One for Open Source which doesn't need secrets (tyk license). And the other which needs the license. When reviewing an external PR from a fork, the Open Source action should pass, and the one which needed the license fails at the license check step, we then can manually check/test & if it looks OK, we can merge. It's not ideal, but it kind of works for the short-term. If you find a better longer term solution, please advise & we can update tyk-operator CI also.

**Comment by excieve** [comment]
@asoorm I think it's a fundamental issue of running potentially untrusted code in an environment with secrets.

**Comment by excieve** [comment]
@drpebcak We've pushed some CI changes to master. Could you please merge them into your branch?

**Comment by drpebcak** [comment]
@excieve done!

**Review by excieve — APPROVED** [review]
Thanks @drpebcak!

**Pull request merged**
