### PR TITLE
[TD-44] deprecating tyk-k8s, referring user to tyk-operator

### PR DESCRIPTION
**Pull request by asoorm**

### CODE REVIEW

**Comment by joshblakeley** [comment]
Good start here, the helm notes files probably need cleaning up too.

**Comment by excieve** [comment]
I think it depends on #73 in a way as it's more than just documenting the fact.

**Comment by vesko-tyk** [comment]
Inside all charts there is configmaps, ingress resources, secrets, certificates referring to tyk-k8s. All this needs to be cleaned as well. Also in the Readme file we ask people to create namespace named tyk-ingress and use it after it, this would need to be changed as well since we're removing this feature from it.

**Comment by joshblakeley** [comment]
Is there any progress on this @asoorm ?

**Comment by asoorm** [comment]
> Is there any progress on this @asoorm ?

Nop - I thought @vesko-tyk was taking over.

**Comment by joshblakeley** [comment]
> > Is there any progress on this @asoorm ?
> 
> Nop - I thought @vesko-tyk was taking over.

Seem like it is worth catching up together manage expectations on this then otherwise it seems at risk

**Comment by vesko-tyk** [comment]
@joshblakeley @asoorm I believe this PR can be closed now in favour of this one: https://github.com/TykTechnologies/tyk-helm-chart/pull/73/

In PR: https://github.com/TykTechnologies/tyk-helm-chart/pull/73/ I'm addressing the deprecation of tyk-k8s and introducing fully automated bootstrap process.

**Pull request closed without merging**
