### PR TITLE
[TD-244] Add lint and tests

### PR DESCRIPTION
**Pull request by abhishiekgowtham**
This PR should allow to run additional tests (use --upgrade in ct install to test upgrading charts) and lint every pull request.

### CODE REVIEW

**Review by excieve — APPROVED** [review]
Looks good, thanks @abhishiekgowtham!

Does it depend on #108 to be merged first (Kind manifest)?

**Comment by abhishiekgowtham** [comment]
Yes @excieve! Need to merge #108 first.

**Review by gwotg — APPROVED** [review]
Looks great @abhishiekgowtham

**Comment by asoorm** [comment]
> Do we want to add any information to the secret name about expiration? Could raise awareness by just reading.

This is how we check expiry in the operator. That way the test fails if the key is expired & we are alerted via GH actions.

https://github.com/TykTechnologies/tyk-operator/blob/master/.github/workflows/pro.yaml#L38-L40

**Comment by abhishiekgowtham** [comment]
Awesome, Thanks @asoorm! Will update the PR to include that step.

**Pull request merged**
