### PR TITLE
Add extraVolumes and extraVolumeMounts to enterprise-portal StatefulSet

### PR DESCRIPTION
**Pull request by LoopKarma**
## Description
In order to run enterprise portal I need to mount folder with credentials, but extraVolumes and extraVolumeMounts were not supported by enterprise-portal StatefulSet

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by esttorhe — APPROVED** [review]

**Review by diseku — APPROVED** [review]

**Comment by buraksekili** [comment]
thanks @LoopKarma for the contribution, lgtm!

**Review by buraksekili — APPROVED** [review]

**Comment by LoopKarma** [comment]
@buraksekili thank you. could you suggest what should be done to make smoke test pass? Not really clear the reason of failure..

**Comment by buraksekili** [comment]
> @buraksekili thank you. could you suggest what should be done to make smoke test pass? Not really clear the reason of failure..

@LoopKarma, the reason why tests are failed is that they try to deploy `tyk-pro` which requires a license to be deployed. Our CI is able to generate licenses for any PR coming from people within @TykTechnologies. Since license is a secret in the CI, PRs coming from outside of the organization cannot access the license which causes a failure in the smoke tests.
So, you do not need to change anything, this is expected behaviour.

Also, we are in the middle of switching the new helm charts (https://github.com/TykTechnologies/tyk-charts/) which provides a more modular way to deploy Tyk stack. And enterprise portal PR will be merged soon :) So, you can also check the new repo. 

Thank you again contribution. Feel free to tag me if you need anything

**Comment by caroltyk** [comment]
extraVolumes and extraVolumeMounts are supported in our new Helm Chart.

The new Helm chart for developer portal is available at [ArtifactHub](https://artifacthub.io/packages/helm/tyk-helm/tyk-dev-portal) and [GitHub](https://github.com/TykTechnologies/tyk-charts/tree/main/components/tyk-dev-portal)

Please refer to our [Installation guide](https://tyk.io/docs/product-stack/tyk-enterprise-developer-portal/deploy/install-tyk-enterprise-portal/install-portal-using-new-helm/) for more details!

**Pull request closed without merging**
